const jobs = [
{
  id: 1,
  title: "SDE Intern",
  company: "Amazon",
  location: "Hyderabad",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Java", "Data Structures", "Problem Solving"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "₹40k–₹80k/month Internship",
  applyUrl: "https://amazon.jobs/jobs/123456",
  description: "Join our core team to build scalable services. You will work on real-world projects that impact millions of customers. Strong focus on backend optimization and distributed systems."
},
{
  id: 2,
  title: "Junior Backend Developer",
  company: "Flipkart",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "0-1",
  skills: ["Node.js", "Express", "MongoDB"],
  source: "Naukri",
  postedDaysAgo: 3,
  salaryRange: "10–18 LPA",
  applyUrl: "https://www.flipkartcareers.com/details/456",
  description: "Collaborate with talented engineers to enhance our e-commerce platform. You will be responsible for developing new features and maintaining existing APIs. High ownership and fast-paced environment."
},
{
  id: 3,
  title: "React Developer",
  company: "Razorpay",
  location: "Remote",
  mode: "Remote",
  experience: "1-3",
  skills: ["React", "TypeScript", "Tailwind CSS"],
  source: "LinkedIn",
  postedDaysAgo: 0,
  salaryRange: "12–22 LPA",
  applyUrl: "https://razorpay.com/jobs/react-dev",
  description: "Craft seamless payment experiences for businesses worldwide. Help us build high-performance frontend components. Focus on UI/UX excellence and component architectural design."
},
{
  id: 4,
  title: "Data Analyst Intern",
  company: "Swiggy",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["SQL", "Python", "Tableau"],
  source: "Indeed",
  postedDaysAgo: 2,
  salaryRange: "₹25k–₹45k/month Internship",
  applyUrl: "https://careers.swiggy.com/data-analyst",
  description: "Help us derive insights from massive datasets to optimize delivery routes and customer satisfaction. Deep dive into operational metrics. Perfect for curious minds who love storytelling with numbers."
},
{
  id: 5,
  title: "Java Developer",
  company: "TCS",
  location: "Pune",
  mode: "Onsite",
  experience: "0-1",
  skills: ["Java", "Spring Boot", "MySQL"],
  source: "Naukri",
  postedDaysAgo: 5,
  salaryRange: "3.5–6 LPA",
  applyUrl: "https://www.tcs.com/careers/java-dev",
  description: "Join our banking and financial services division. Develop robust enterprise applications for global clients. Learn and implement clean coding practices in a structured corporate environment."
},
{
  id: 6,
  title: "Frontend Intern",
  company: "Zoho",
  location: "Chennai",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["HTML", "CSS", "JavaScript"],
  source: "LinkedIn",
  postedDaysAgo: 4,
  salaryRange: "₹15k–₹30k/month Internship",
  applyUrl: "https://www.zoho.com/careers/frontend-intern",
  description: "Work on world-class SaaS products from the ground up. You will learn modern frontend frameworks while tackling UI challenges. Mentorship provided by industry veterans in a culture of pure engineering."
},
{
  id: 7,
  title: "Graduate Engineer Trainee",
  company: "Infosys",
  location: "Mysuru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["C++", "Python", "Logical Reasoning"],
  source: "Indeed",
  postedDaysAgo: 8,
  salaryRange: "3.6–5 LPA",
  applyUrl: "https://www.infosys.com/get- Mysore",
  description: "Start your career with one of the world's most innovative IT firms. Undergo intensive training on digital technologies. Participate in global projects and learn software development life cycle end-to-end."
},
{
  id: 8,
  title: "Python Developer",
  company: "PhonePe",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "Fresher",
  skills: ["Python", "Django", "Cloud Fundamentals"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "8–14 LPA",
  applyUrl: "https://www.phonepe.com/careers/python",
  description: "Build robust backend services for India's leading digital payments app. Scale systems to handle billions of transactions every month. Focus on high availability and low-latency system design."
},
{
  id: 9,
  title: "QA Intern",
  company: "CRED",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Selenium", "Automation Testing", "Manual Testing"],
  source: "Naukri",
  postedDaysAgo: 2,
  salaryRange: "₹30k–₹50k/month Internship",
  applyUrl: "https://careers.cred.club/qa-intern",
  description: "Ensure the highest quality of the CRED mobile and web app. Participate in automated test suite creation. Identify bugs before they reach our premium members. High bar for detail and design."
},
{
  id: 10,
  title: "Full Stack Developer",
  company: "Paytm",
  location: "Noida",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["React", "Node.js", "Redis"],
  source: "LinkedIn",
  postedDaysAgo: 6,
  salaryRange: "12–20 LPA",
  applyUrl: "https://paytm.com/careers/full-stack",
  description: "Build both frontend and backend for our financial ecosystem. Own features from inception to deployment. Optimize for high traffic during peak sale events using cutting-edge caching strategies."
},
{
  id: 11,
  title: "Software Engineer",
  company: "Zomato",
  location: "Gurugram",
  mode: "Onsite",
  experience: "0-1",
  skills: ["Golang", "Microservices", "PostgreSQL"],
  source: "Indeed",
  postedDaysAgo: 3,
  salaryRange: "12–18 LPA",
  applyUrl: "https://www.zomato.com/careers/se",
  description: "Engineer the backbone of food delivery in India. Work on real-time order tracking and dispatch algorithms. Optimize backend services for extreme concurrency and low response times."
},
{
  id: 12,
  title: "Cloud Support Intern",
  company: "IBM",
  location: "Remote",
  mode: "Remote",
  experience: "Fresher",
  skills: ["AWS", "Docker", "Linux"],
  source: "LinkedIn",
  postedDaysAgo: 9,
  salaryRange: "₹20k–₹35k/month Internship",
  applyUrl: "https://www.ibm.com/it-jobs/cloud-support",
  description: "Assist clients in migrating and managing workloads on IBM Cloud. Learn about containerization and Kubernetes first-hand. Troubleshoot complex infrastructure issues in an enterprise setting."
},
{
  id: 13,
  title: "Junior Java Developer",
  company: "Cognizant",
  location: "Kolkata",
  mode: "Hybrid",
  experience: "0-1",
  skills: ["Java", "Hibernate", "Microservices"],
  source: "Naukri",
  postedDaysAgo: 7,
  salaryRange: "4–7 LPA",
  applyUrl: "https://careers.cognizant.com/java-jr",
  description: "Develop digital solutions for insurance and healthcare sectors. Work with advanced Java frameworks. Part of a collaborative team focusing on agile development and continuous integration."
},
{
  id: 14,
  title: "Backend Developer (Python)",
  company: "Freshworks",
  location: "Chennai",
  mode: "Onsite",
  experience: "1-3",
  skills: ["Python", "Flask", "Kafka"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "14–24 LPA",
  applyUrl: "https://www.freshworks.com/backend-developer",
  description: "Scale our customer engagement platform to serve over 50,000 businesses globally. Design asynchronous architectures and streaming pipelines. Focus on stability and extensibility of core API services."
},
{
  id: 15,
  title: "SDE-1",
  company: "Juspay",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Haskell", "Functional Programming", "Logic"],
  source: "Indeed",
  postedDaysAgo: 0,
  salaryRange: "18–24 LPA",
  applyUrl: "https://juspay.in/careers/sde1",
  description: "Join the team that processes majority of UPI transactions in India. Master functional programming to build highly reliable payment SDKs. Intellectual challenge guaranteed for high-level problem solvers."
},
{
  id: 16,
  title: "Junior Frontend Developer",
  company: "CRED",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "0-1",
  skills: ["React", "Next.js", "Framer Motion"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "15–25 LPA",
  applyUrl: "https://careers.cred.club/front-dev",
  description: "Translate high-fidelity designs into pixel-perfect web experiences. Use modern animation libraries to create delight. Maintain the premium engineering standard CRED is known for."
},
{
  id: 17,
  title: "Associate Software Engineer",
  company: "Accenture",
  location: "Hyderabad",
  mode: "Remote",
  experience: "Fresher",
  skills: ["SQL", "Java", "Salesforce"],
  source: "Naukri",
  postedDaysAgo: 6,
  salaryRange: "4.5–7 LPA",
  applyUrl: "https://www.accenture.com/ase-job",
  description: "Kickstart your career in technology consulting. Learn to leverage enterprise platforms to solve business problems. Work across diverse industries like retail, pharma, and finance."
},
{
  id: 18,
  title: "DevOps Intern",
  company: "PhonePe",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "Fresher",
  skills: ["Terraform", "Ansible", "Jenkins"],
  source: "LinkedIn",
  postedDaysAgo: 3,
  salaryRange: "₹35k–₹55k/month Internship",
  applyUrl: "https://www.phonepe.com/devops-intern",
  description: "Automation is at our core. Help us build 'Infrastructure as Code' for high-traffic servers. Learn how we deploy changes hundreds of times a day with zero downtime."
},
{
  id: 19,
  title: "Junior Data Engineer",
  company: "Capgemini",
  location: "Gurugram",
  mode: "Onsite",
  experience: "0-1",
  skills: ["PySpark", "ETL", "Hive"],
  source: "Naukri",
  postedDaysAgo: 8,
  salaryRange: "5–8 LPA",
  applyUrl: "https://capgemini.com/data-eng",
  description: "Manage data pipelines for large-scale analytics projects. Work with Hadoop ecosystem and modern data warehouses. Ensure data quality and integrity across the organization's data lake."
},
{
  id: 20,
  title: "UI/UX Designer Intern",
  company: "Zomato",
  location: "Gurugram",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Figma", "User Research", "Prototyping"],
  source: "Indeed",
  postedDaysAgo: 1,
  salaryRange: "₹25k–₹45k/month Internship",
  applyUrl: "https://zomato.com/careers/design-intern",
  description: "Design interfaces for the next 100 million foodies. Conduct user studies and iterate on mobile designs. Directly impact the food ordering and delivery experience of millions."
},
{
  id: 21,
  title: "MERN Stack Developer",
  company: "Groww",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["React", "Express", "MongoDB", "Node.js"],
  source: "LinkedIn",
  postedDaysAgo: 4,
  salaryRange: "14–22 LPA",
  applyUrl: "https://groww.in/careers/mern",
  description: "Build seamless investing experiences. Simplify complex financial data into beautiful, easy-to-use charts and interfaces. Help Indians participate in the stock market with confidence."
},
{
  id: 22,
  title: "Android Developer",
  company: "Ola Cabs",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "1-3",
  skills: ["Kotlin", "Jetpack Compose", "Coroutines"],
  source: "Linkedin",
  postedDaysAgo: 2,
  salaryRange: "16–26 LPA",
  applyUrl: "https://www.ola.com/android-dev",
  description: "Re-engineer our flagship ride-hailing app. Focus on map integrations and real-time updates. Optimize battery consumption and app performance for diverse mobile devices."
},
{
  id: 23,
  title: "JavaScript Engineer",
  company: "Postman",
  location: "Remote",
  mode: "Remote",
  experience: "1-3",
  skills: ["JavaScript", "Electron", "API Design"],
  source: "LinkedIn",
  postedDaysAgo: 0,
  salaryRange: "20–35 LPA",
  applyUrl: "https://www.postman.com/js-eng",
  description: "Work on the world's leading API platform. Improve the desktop experience and build tools that millions of developers use daily. Deep dive into JS internals and Electron optimization."
},
{
  id: 24,
  title: "Systems Engineer (Fresher)",
  company: "Dell",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["C", "System Design", "Networking"],
  source: "Indeed",
  postedDaysAgo: 10,
  salaryRange: "7–10 LPA",
  applyUrl: "https://jobs.dell.com/se-fresher",
  description: "Dive into the world of hardware and software integration. Develop firmware and system-level software for next-gen computing devices. Learn about server architectures and high-performance computing."
},
{
  id: 25,
  title: "Junior Security Engineer",
  company: "Paytm",
  location: "Noida",
  mode: "Hybrid",
  experience: "0-1",
  skills: ["Pentesting", "OWASP", "Cybersecurity"],
  source: "LinkedIn",
  postedDaysAgo: 5,
  salaryRange: "9–15 LPA",
  applyUrl: "https://paytm.com/security-eng",
  description: "Guard the financial data of millions. Conduct vulnerability assessments and code reviews. Stay ahead of emerging threats in the fintech space and ensure a zero-breach environment."
},
{
  id: 26,
  title: "C# Developer",
  company: "Oracle",
  location: "Hyderabad",
  mode: "Onsite",
  experience: "1-3",
  skills: ["C#", ".NET Core", "SQL Server"],
  source: "Naukri",
  postedDaysAgo: 3,
  salaryRange: "12–20 LPA",
  applyUrl: "https://oracle.com/net-dev",
  description: "Build enterprise cloud applications for international corporations. Develop scalable backend services using .NET. Work in a highly professional environment focused on quality and scale."
},
{
  id: 27,
  title: "Software Engineer Intern",
  company: "Google",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Python", "Algorithms", "Mathematics"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "₹80k–₹120k/month Internship",
  applyUrl: "https://google.com/interns",
  description: "Solve complex computational problems alongside world-class engineers. Enhance features on Search, Maps, or Cloud. A rare opportunity to start your career at the frontiers of technology."
},
{
  id: 28,
  title: "Web Developer (React)",
  company: "Meesho",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "0-1",
  skills: ["React", "CSS Modules", "Redux"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "8–13 LPA",
  applyUrl: "https://meesho.com/web-dev",
  description: "Empower small business owners across India with a simple yet powerful e-commerce interface. Focus on loading speeds and mobile-web performance optimization."
},
{
  id: 29,
  title: "ML Intern",
  company: "Flipkart",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Scikit-learn", "PyTorch", "Data Science"],
  source: "LinkedIn",
  postedDaysAgo: 4,
  salaryRange: "₹40k–₹65k/month Internship",
  applyUrl: "https://flipkart.com/ml-intern",
  description: "Improve our recommendation engine using state-of-the-art machine learning models. Work on search ranking and fraud detection. Translate academic papers into production code."
},
{
  id: 30,
  title: "Junior Project Coordinator",
  company: "Wipro",
  location: "Pune",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Excel", "Communication", "Management"],
  source: "Indeed",
  postedDaysAgo: 9,
  salaryRange: "3–4.5 LPA",
  applyUrl: "https://wipro.com/pc-job",
  description: "Ensure smooth delivery of software projects. Coordinate between technical teams and stakeholders. Track deadlines and assist in resource planning for diverse global accounts."
},
{
  id: 31,
  title: "Full Stack Intern",
  company: "Zerodha",
  location: "Bengaluru",
  mode: "Remote",
  experience: "Fresher",
  skills: ["Go", "Vue.js", "Postgres"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "₹50k/month Internship",
  applyUrl: "https://zerodha.tech/fullstack",
  description: "Join India's leanest and largest stock brokerage tech team. Build systems from first principles. High standard for clean code and minimalist product design. Remote-friendly culture."
},
{
  id: 32,
  title: "Associate Software Engineer",
  company: "SAP",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["ABAP", "Java", "Enterprise Architecture"],
  source: "LinkedIn",
  postedDaysAgo: 6,
  salaryRange: "9–13 LPA",
  applyUrl: "https://sap.com/ase-india",
  description: "Build business software that runs the world. Learn ABAP and core ERP systems. Work on digital transformation projects for global Fortune 500 companies."
},
{
  id: 33,
  title: "Node.js Developer",
  company: "Tickr",
  location: "Remote",
  mode: "Remote",
  experience: "0-1",
  skills: ["Node.js", "Redis", "Sockets"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "6–10 LPA",
  applyUrl: "https://tickr.com/careers/node",
  description: "Build real-time stock monitoring dashboards. Work with high-frequency data streams and WebSocket connections. Focus on backend performance and low-latency delivery."
},
{
  id: 34,
  title: "Cloud Architect Intern",
  company: "Amazon Web Services (AWS)",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "Fresher",
  skills: ["Cloud Computing", "Architecture", "Python"],
  source: "LinkedIn",
  postedDaysAgo: 3,
  salaryRange: "₹45k–₹70k/month Internship",
  applyUrl: "https://amazon.jobs/aws-intern",
  description: "Learn how to design highly available and resilient systems on the world's most comprehensive cloud. Shadow senior architects on customer projects. Great exposure for future cloud specialists."
},
{
  id: 35,
  title: "Technical Support Engineer",
  company: "Freshworks",
  location: "Chennai",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Troubleshooting", "Networking", "Soft Skills"],
  source: "Indeed",
  postedDaysAgo: 5,
  salaryRange: "4–6 LPA",
  applyUrl: "https://freshworks.com/support-eng",
  description: "Be the face of our tech support to global businesses. Solve complex product queries and bridge the gap between customers and engineers. Rapid career growth path into CSM or Dev roles."
},
{
  id: 36,
  title: "React Native Developer",
  company: "Zepto",
  location: "Mumbai",
  mode: "Onsite",
  experience: "1-3",
  skills: ["React Native", "JavaScript", "Animation"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "16–28 LPA",
  applyUrl: "https://www.zepto.com/careers-rn",
  description: "Build the fastest grocery delivery experience. Focus on mobile app stability and fluid checkout flows. Optimize for 10-minute delivery precision across various mobile network conditions."
},
{
  id: 37,
  title: "Quality Analyst",
  company: "Infosys",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["JMeter", "Performance Testing", "CI/CD"],
  source: "Naukri",
  postedDaysAgo: 4,
  salaryRange: "6–10 LPA",
  applyUrl: "https://infosys.com/qa-job",
  description: "Carry out large-scale performance tests for enterprise applications. Ensure stability under heavy load. Work with cloud-native monitoring tools to identify performance bottlenecks."
},
{
  id: 38,
  title: "Data Scientist",
  company: "Delhivery",
  location: "Gurugram",
  mode: "Onsite",
  experience: "1-3",
  skills: ["Statistics", "Deep Learning", "SQL"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "18–30 LPA",
  applyUrl: "https://delhivery.com/ds-role",
  description: "Solve logistics problems using data science. Optimize warehouse operations and delivery networks. Use machine learning to predict demand and delivery times accurately across India."
},
{
  id: 39,
  title: "DevOps Engineer",
  company: "Razorpay",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["Kubernetes", "Azure", "Security"],
  source: "Indeed",
  postedDaysAgo: 0,
  salaryRange: "20–35 LPA",
  applyUrl: "https://razorpay.com/devops-eng",
  description: "Manage the infrastructure of India's payment backbone. Implement high-security cloud features and automate production deployments. Ensure near-perfect uptime for millions of end users."
},
{
  id: 40,
  title: "SDE Intern (Frontend)",
  company: "Upstox",
  location: "Mumbai",
  mode: "Hybrid",
  experience: "Fresher",
  skills: ["React", "HTML/CSS", "Design Systems"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "₹35k–₹50k/month Internship",
  applyUrl: "https://upstox.com/frontend-intern",
  description: "Craft pixel-perfect trading experiences for retail investors. Collaborate closely with designers to build reusable component libraries. Participate in code reviews and learn best practices."
},
{
  id: 41,
  title: "Junior Backend Eng",
  company: "Hike",
  location: "Remote",
  mode: "Remote",
  experience: "0-1",
  skills: ["Node.js", "Redis", "Distributed Systems"],
  source: "LinkedIn",
  postedDaysAgo: 3,
  salaryRange: "12–18 LPA",
  applyUrl: "https://hike.in/be-jr",
  description: "Build for the metaverse and virtual social worlds. Engineer high-performance web systems that support millions of concurrent avatar interactions. Low-latency backend is our top priority."
},
{
  id: 42,
  title: "iOS Intern",
  company: "Cult.fit",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Swift", "iOS SDK", "UI Kit"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "₹30k–₹45k/month Internship",
  applyUrl: "https://cult.fit/ios-intern",
  description: "Help us build the most engaging health and fitness app in India. Learn the nuances of iOS development. Focus on smooth animations and robust offline-first functionality."
},
{
  id: 43,
  title: "Junior Site Reliability Eng",
  company: "Swiggy",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "0-1",
  skills: ["Go", "Monitoring", "Shell Scripting"],
  source: "Indeed",
  postedDaysAgo: 5,
  salaryRange: "15–22 LPA",
  applyUrl: "https://swiggy.com/sre-jr",
  description: "Keep the food moving. Respond to incidents and build tools to prevent them. Monitor cluster health and optimize observability of critical services during high-traffic lunch/dinner peaks."
},
{
  id: 44,
  title: "Embedded Systems Intern",
  company: "Bosch",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Embedded C", "Microcontrollers", "RTOS"],
  source: "Indeed",
  postedDaysAgo: 10,
  salaryRange: "₹18k–₹30k/month Internship",
  applyUrl: "https://bosch.com/embedded-intern",
  description: "Work on automotive and IoT projects. Write efficient code for low-power devices. Learn about industrial-grade software development and hardware-software co-design."
},
{
  id: 45,
  title: "Junior Python Analyst",
  company: "Mu Sigma",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Python", "Pandas", "Analytical Thinking"],
  source: "Naukri",
  postedDaysAgo: 7,
  salaryRange: "4–6 LPA",
  applyUrl: "https://mu-sigma.com/pa-job",
  description: "Solve business problems for global giants. Use Python to process data and extract actionable insights. A high-learning environment for aspiring data professionals and decision scientists."
},
{
  id: 46,
  title: "Frontend Developer (Vue)",
  company: "HackerRank",
  location: "Remote",
  mode: "Remote",
  experience: "1-3",
  skills: ["Vue.js", "JavaScript", "XSS Security"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "18–28 LPA",
  applyUrl: "https://hackerrank.com/vue-dev",
  description: "Maintain the platform where the world hires developers. Focus on secure and accessible UI components. Work with an engineering team that values developer experience and high code quality."
},
{
  id: 47,
  title: "Content Designer Intern",
  company: "Canva",
  location: "Remote",
  mode: "Remote",
  experience: "Fresher",
  skills: ["Copywriting", "Branding", "Visual Design"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "₹20k–₹40k/month Internship",
  applyUrl: "https://canva.com/design-intern-remote",
  description: "Help build the future of visual communication. Create guides and content that empower millions to design anything. A creative role for individuals with a flair for visual storytelling."
},
{
  id: 48,
  title: "Junior Rails Developer",
  company: "Airbase",
  location: "Bengaluru",
  mode: "Hybrid",
  experience: "0-1",
  skills: ["Ruby on Rails", "React", "Postgres"],
  source: "LinkedIn",
  postedDaysAgo: 4,
  salaryRange: "15–25 LPA",
  applyUrl: "https://airbase.com/rails-jr",
  description: "Build the leading spend management platform. Work with a mature Ruby on Rails codebase. Learn how to manage complex financial entities and payment workflows with high precision."
},
{
  id: 49,
  title: "Systems Engineer Trainee",
  company: "LTI Mindtree",
  location: "Pune",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Java", "PL/SQL", "Aptitude"],
  source: "Indeed",
  postedDaysAgo: 9,
  salaryRange: "3.5–5 LPA",
  applyUrl: "https://ltimindtree.com/trainee",
  description: "Start your tech journey in a top-tier IT services firm. Get trained in multiple tech stacks and work on live projects for global clients. A great platform for foundational technical growth."
},
{
  id: 50,
  title: "Product Intern",
  company: "Dunzo",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Product Roadmap", "Analytics", "Wireframing"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "₹25k–₹40k/month Internship",
  applyUrl: "https://dunzo.com/product-intern",
  description: "Learn how products are built and scaled in the hyper-local delivery space. Assist PMs in feature research and user feedback loop analysis. Great for aspiring product managers."
},
{
  id: 51,
  title: "Junior Backend (Java)",
  company: "Oracle",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "1-3",
  skills: ["Java", "Spring", "Oracle DB"],
  source: "Naukri",
  postedDaysAgo: 3,
  salaryRange: "14–22 LPA",
  applyUrl: "https://oracle.com/java-be",
  description: "Work on cloud-scale database services. Develop high-performance Java code that ensures data persistence for major enterprises. Focus on concurrency, memory management, and system design."
},
{
  id: 52,
  title: "Salesforce Developer",
  company: "Cognizant",
  location: "Hyderabad",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["Apex", "LWC", "Salesforce CRM"],
  source: "LinkedIn",
  postedDaysAgo: 5,
  salaryRange: "7–11 LPA",
  applyUrl: "https://cognizant.com/sf-dev",
  description: "Customize and build on the world's #1 CRM platform. Help clients optimize their sales and service processes. Use modern Lightning Web Components for high-performance frontend interfaces."
},
{
  id: 53,
  title: "UI Intern",
  company: "Urban Company",
  location: "Gurugram",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["CSS", "React", "Visual Fine-tuning"],
  source: "LinkedIn",
  postedDaysAgo: 2,
  salaryRange: "₹30k–₹45k/month Internship",
  applyUrl: "https://urbancompany.com/ui-intern",
  description: "Fine-tune UI details across our services app. Work with the design team to ensure visual consistency. Learn the balance between aesthetics and high-impact functional design."
},
{
  id: 54,
  title: "Cloud Support Eng",
  company: "Microsoft",
  location: "Hyderabad",
  mode: "Onsite",
  experience: "0-1",
  skills: ["Azure", "Networking", "Win Server"],
  source: "Indeed",
  postedDaysAgo: 6,
  salaryRange: "10–16 LPA",
  applyUrl: "https://microsoft.com/cloud-support-role",
  description: "Empower customers through deep technical problem solving on Azure. Work on cutting-edge cloud infrastructure. Influence product improvements by identifying recurring customer pain-points."
},
{
  id: 55,
  title: "Junior Frontend Eng",
  company: "PocketFM",
  location: "Remote",
  mode: "Remote",
  experience: "0-1",
  skills: ["React", "State Management", "Audio APIs"],
  source: "LinkedIn",
  postedDaysAgo: 1,
  salaryRange: "12–18 LPA",
  applyUrl: "https://pocketfm.in/frontend-jr",
  description: "Build UI for India's leading audio-streaming app. Research and optimize player performance. Work on discovery experiences for millions of listeners around the globe."
},
{
  id: 56,
  title: "Business Analyst Intern",
  company: "TCS",
  location: "Mumbai",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Requirement Gathering", "Excel", "UML"],
  source: "Naukri",
  postedDaysAgo: 7,
  salaryRange: "₹12k–₹25k/month Internship",
  applyUrl: "https://tcs.com/ba-intern",
  description: "Liaise between clients and tech teams. Document requirements and create process flow diagrams. Gain exposure to enterprise business modeling and IT consulting workflows."
},
{
  id: 57,
  title: "QA Automation Eng",
  company: "CleverTap",
  location: "Mumbai",
  mode: "Hybrid",
  experience: "1-3",
  skills: ["Playwright", "Cypress", "JavaScript"],
  source: "LinkedIn",
  postedDaysAgo: 4,
  salaryRange: "12–20 LPA",
  applyUrl: "https://clevertap.com/qa-auto",
  description: "Automate E2E testing for our high-scale user engagement platform. Ensure stability across millions of user events. Work with the latest testing frameworks and CI/CD pipelines."
},
{
  id: 58,
  title: "Junior DevOps Eng",
  company: "Capgemini",
  location: "Pune",
  mode: "Onsite",
  experience: "0-1",
  skills: ["CI/CD", "AWS", "Grafana"],
  source: "Indeed",
  postedDaysAgo: 8,
  salaryRange: "6–9 LPA",
  applyUrl: "https://capgemini.com/devops-pune",
  description: "Assist in managing cloud infrastructure and build pipelines. Help teams move towards more reliable delivery methods. Hands-on experience with cloud-native monitoring and deployment tools."
},
{
  id: 59,
  title: "React Developer",
  company: "Spinny",
  location: "Gurugram",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["React", "Tailwind", "Next.js"],
  source: "LinkedIn",
  postedDaysAgo: 0,
  salaryRange: "8–12 LPA",
  applyUrl: "https://spinny.com/careers-react",
  description: "Build trust through technology in the used-car market. Develop clean and fast web interfaces for car discovery and inspection reports. Focus on user experience and web performance."
},
{
  id: 60,
  title: "SDE Intern",
  company: "Ola",
  location: "Bengaluru",
  mode: "Onsite",
  experience: "Fresher",
  skills: ["Java", "Go", "Architecture"],
  source: "Indeed",
  postedDaysAgo: 3,
  salaryRange: "₹40k–₹60k/month Internship",
  applyUrl: "https://ola.com/sde-intern",
  description: "Dive deep into the world of mobility tech. Solve problems relating to mapping, dispatching, and pricing. Participate in high-impact projects that define how India moves."
}
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobs;
}
